language: node_js
node_js: [ '10' ]
cache: yarn
sudo: required

services:
  - docker

install: yarn
script: yarn test

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
    # tags: true
