language: node_js
node_js: [ '10' ]
cache: yarn
sudo: required

services:
  - docker

install: yarn
script: yarn test

deploy:
  provider: script
  script: export DOCKER_TAG=$TRAVIS_TAG && ./deploy.sh
  on:
    branch: master
    tags: true
