version: '3'
services:
  neo4j:
    image: neo4j:3.3.1
    # volumes:
    #   - neo4-volume:/data
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
  decorator:
    build:
      context: ./
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    ports:
       - "3000:3000"
    depends_on:
       - neo4j
