version: '3'

volumes:
  neo4j-volume:   # neo4j data

services:
  decorator:
    build:
      context: ./
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    environment:
      server_url: ${server_url:-localhost}
      neo4j_url: ${neo4j_url:-neo4j}
    ports:
       - "3000:3000"
    depends_on:
       - neo4j
    volumes:
      - "./routes/config.yml:/usr/src/app/routes/config.yml"

  neo4j:
    build:
      context: ./neo4j
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    volumes:
      - neo4j-volume:/data
      - "./neo4j/conf:/conf"
      - "./neo4j/conf:/var/lib/neo4j/conf"
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      NEO4J_AUTH: none
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
