version: '3.4'

x-proxy: &proxy
  http_proxy: ${http_proxy}
  https_proxy: ${https_proxy}
  no_proxy: ${no_proxy}

volumes:
  neo4j-volume: # neo4j data

services:
  decorator:
    build:
      context: ./
      args:
        <<: *proxy
    environment:
      DECORATOR_CONFIG: ${DECORATOR_CONFIG:-/etc/decorator}
      DECORATOR_URL: ${DECORATOR_URL:-http://localhost:3000}
      DECORATOR_NEO4J_URL: ${DECORATOR_NEO4J_URL:-http://neo4j:7474}
    ports: [ '3000:3000' ]
    depends_on: [ neo4j ]
    volumes: [ './config:/etc/decorator' ]

  neo4j:
    #build:
    #  context: ./neo4j
    #  args:
    #    <<: *proxy
    image: neo4j:3.5.14
    ports: [ '7474:7474', '7473:7473', '7687:7687' ]
    volumes: 
      - neo4j-volume:/data
      - ./neo4j/plugins/:/var/lib/neo4j/plugins
    environment:
      <<: *proxy
      NEO4J_AUTH: none
      NEO4J_dbms_security_procedures_unrestricted: "\\*"
      #NEO4J_dbms_unmanaged__extension__classes: "org.neo4j.graphql=/graphql"
