server_url: 'http://localhost:3000/graph'
neo4j_url: 'http://neo4j:7474/db/data'
decorate:
  _all: {}
  _node:
    data:
      links:
        - title: Expand...
          href: '{{config.server_url}}/cypher'
          method: 'POST'
          body:
            query: 'MATCH (u)-[e]-(v) WHERE ID(u)={{doc.metadata.id}} RETURN u,e,v'
  _edge:
    data:
      links:
        - title: Expand...
          href: '{{config.server_url}}/cypher'
          method: 'POST'
          body:
            query: 'MATCH (u)-[e]-(v) WHERE ID(e)={{doc.metadata.id}} RETURN u,e,v'
  Person:
    data:
      links:
        - title: "Google '{{doc.data.name}}'..."
          href: 'https://www.google.de/search?q={{doc.data.name}}'

decorate_transactional:
  _all: {}
  _node: {}
  _edge: {}
  Person:
    properties:
      links:
        - title: "Google '{{doc.properties.name}}'"
          href: 'https://www.google.de/search?q={{doc.properties.name}}'
