server_url: '{{ env.DECORATOR_URL | default("http://localhost:3000", true) }}/graph'
neo4j_url: '{{ env.DECORATOR_NEO4J_URL | default("http://neo4j:7474", true) }}/db/data'
decorate:
  _all: {}
  _node:
    data:
      links:
        - title: Expand...
          href: '{{config.server_url}}/cypher'
          method: 'POST'
          body:
            query: 'MATCH (u)-[e]-(v) WHERE ID(u)={{doc.metadata.id}} RETURN u,e,v'
  _edge:
    data:
      links:
        - title: Expand...
          href: '{{config.server_url}}/cypher'
          method: 'POST'
          body:
            query: 'MATCH (u)-[e]-(v) WHERE ID(e)={{doc.metadata.id}} RETURN u,e,v'

decorate_transactional:
  _all: {}
  _node: {}
  _edge: {}
